# Generated by Django 5.1 on 2024-08-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0003_menulink_site_setup_sitesetup_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='favicon',
        ),
    ]
